version: '3.9'
services:
  db:
    image: postgres:latest
    environment:
      POSTGRES_USER: django_admin_user
      POSTGRES_PASSWORD: django_admin_password
      POSTGRES_DB: django_database
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  redis:
    image: redis:latest
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data

  # web:
  #   build: .
  #   command: python manage.py runserver 0.0.0.0:8000
  #   ports:
  #     - "8000:8000"
  #   depends_on:
  #     - db
  #     - redis